apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-worker
  namespace: sprawdzaniekierowcow
  labels:
    app: validation-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation-worker
  strategy:
    type: Recreate # Only one worker at a time
  template:
    metadata:
      labels:
        app: validation-worker
    spec:
      restartPolicy: Always
      containers:
        - name: worker
          image: ghcr.io/tobiasz-gleba/sprawdzaniekierowcow.pl:20251023153843 # {"$imagepolicy": "sprawdzaniekierowcow:sprawdzaniekierowcow"}
          command: ['npm', 'run', 'worker:validate']
          workingDir: /app
          env:
            - name: DB_HOST
              value: mysql.sprawdzaniekierowcow.svc.cluster.local
            - name: DB_USERNAME
              value: sprawdzaniekierowcow
            - name: DB_NAME
              value: sprawdzaniekierowcow
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: github-settings
                  key: SHARED_DB_PASSWORD
                  optional: false
            - name: WORKER_POLL_INTERVAL
              value: '3000' # 3 seconds between queue checks
            - name: WORKER_DELAY
              value: '2000' # 2 seconds between validations
            - name: NODE_ENV
              value: 'production'
          resources:
            limits:
              memory: '2Gi'
              cpu: '1000m'
            requests:
              memory: '512Mi'
              cpu: '250m'
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - 'ps aux | grep -v grep | grep "validation-worker" || exit 1'
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
